config/routes.rb
SnsStudy::Application.routes.draw do
devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :snsstudies do 
     member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :tsubyakis, only: [:create, :destroy]
  resources :messages

  root 'snsstudies#index'

  match '/signup',  to: 'snsstudies#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/snsstudy.rb
class Snsstudy < ActiveRecord::Base
 before_create :create_remember_token

 has_many :tsubyakis, dependent: :destroy
 belongs_to :user

#relationshipsのfollower_idを使用するのでforeign_keyで明示する　 follower_id=snsstudies_id
 has_many :relationships, foreign_key: "follower_id", dependent: :destroy

#followed_id(=snsstudies_id)をfollowed_users配列へ　自分がフォローしているユーザー
#sourceパラメーターからfollowed_users配列の元はfollowed idの集合であることを明示的にRailsに伝えます。
 has_many :followed_users, through: :relationships, source: :followed

#relationshipsのfollowed_idを使用するのでforeign_keyで明示する  followed_id=snsstudies_id
 has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
#関連テーブルから先のモデルにアクセスするための(関連モデルから見た)関連名を入れる。
#sourceキーを省略してもよい :followers属性の場合、Railsが “followers” を単数形にして自動的に外部キーfollower_idを探して
 has_many :followers, through: :reverse_relationships, source: :follower

 has_many :messages, dependent: :destroy

 has_secure_password
 #before_create :create_remember_token

#emailの大文字入力を小文字へ変換
 before_save { self.email = email.downcase }
 validates :name, presence: true, length: { maximum: 50 }
 VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
 #大文字と小文字を区別するか case_sensitive false
 validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },uniqueness: { case_sensitive: false }

 validates :password, presence: true, length: { minimum: 6 }
 validates :password_confirmation, presence: true, length: { minimum: 6 }

#自分自身とフォーローした人のつぶやき
 def tsubyaki_matome
    Tsubyaki.from_users_followed_by(self)
 end

#SecureRandomで衝突しないユニークな文字列を生成する
 def Snsstudy.new_remember_token
    SecureRandom.urlsafe_base64
 end


#生成した文字列をSHA1で暗号化
 def Snsstudy.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
 end

#フォローする相手のユーザーがデータベース上に存在するかどうかをチェック
 def following?(other_user)
    #relationships.exists?(followed_id: other_user.id)
    relationships.find_by(followed_id: other_user.id)
 end

#self.relationships.create!
#「フォローする」のリレーションシップを作成します。
 def follow!(other_user)
	#relationshipsにレコードをcreate followed_idは引数
    relationships.create!(followed_id: other_user.id)
 end

#フォローを削除
 def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
 end

 #つぶやき連携の確認
 def tsubuyaki_snsstudy(current)
   Tsubyaki.where("snsstudy_id = ?", current.id)
 end
 
 #他のユーザーにメッセージを送る
 def send_message(snsstudy,message)
   self.messages.create(to_snsstudy_id: snsstudy , messe: message) 
 end


 private
 #remenber_tokenにselfを指定しないとremenber_tokenという名前のローカル変数を作成してしまう。selfを指定することによって、
 #Snsstudyオブジェクトのremember_tokenに値がセットされ、ユーザー保存時に他の属性と一緒にデータベースに書き込まれる
 #(ローカル変数ではなく、DBにしっかりと保存されるようにする。)
 
 def create_remember_token
   self.remember_token = Snsstudy.encrypt(Snsstudy.new_remember_token)

   #p self.remember_token
 end
end

app/controllers/snsstudies_controller.rb
class SnsstudiesController < ApplicationController
  before_action :set_snsstudy, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user,only: [:index, :edit, :update]
  before_action :correct_user,   only: [:edit, :update]

  # GET /snsstudies
  # GET /snsstudies.json
  def index
    @snsstudies = Snsstudy.all
  end

  # GET /snsstudies/1
  # GET /snsstudies/1.json
  def show
   @snsstudies = Snsstudy.all
   #コンフリクトコメント
   #コンフリクトラスト
   #コンフリクト
   #コンフリクト
   #コンフリクト
   @relation=Relationship.all
   #:idのユーザー(/snsstudies/2など。。)を@snsstudyに　
   @snsstudy = Snsstudy.find(params[:id])
   @tsubyakis = @snsstudy.tsubyakis.paginate(page: params[:page])

  #つぶやきが連携されているかpで出力　ターミナルで中身を確認==================
   @aa=Snsstudy.new
   @bb=@aa.tsubuyaki_snsstudy(@snsstudy )
   @cc=Relationship.all
   #
   #
   #テストコミット
   #
   #
   #コンフリクトテスト
   #
   p "出力テスト"
   #tetetetetetetete
   #treteterterterter
   p @cc
   #p @bb
   #p @aa.followed_users
   #hash = {"name"=>"鈴木", "age"=>30}
   #p(hash)
   p "出力テスト"
   
   #scdcsdcscsdcds
   #cscscsdcsdc



  #=====================================================================

  #followed_usersの中身をターミナルで確認==================


  #=====================================================================


   #tsubyakiをbuildでオブジェクト化
   #@tsubyaki = current_user.tsubyakis.build if signed_in?

    if signed_in?
      @tsubyaki = current_user.tsubyakis.build
      @tsubyaki_items = current_user.tsubyaki_matome.paginate(page: params[:page])
    end

   
  end

  # GET /snsstudies/new
  def new
   @snsstudy = Snsstudy.new
  end

  # GET /snsstudies/1/edit
  def edit
  end

  # POST /snsstudies
  # POST /snsstudies.json
  def create
    @snsstudy = Snsstudy.new(snsstudy_params)

    respond_to do |format|
      if @snsstudy.save
        #sign_in(user)　引数に現在の@snsstudy  新しいユーザーを作成したらセッションも作成
        sign_in @snsstudy
        flash[:success] = "Welcome to the Sample App!"
        
        format.html { redirect_to @snsstudy, notice: 'Snsstudy was successfully created.' }
        format.json { render action: 'show', status: :created, location: @snsstudy }
      else
        format.html { render action: 'new' }
        format.json { render json: @snsstudy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /snsstudies/1
  # PATCH/PUT /snsstudies/1.json
  def update
    respond_to do |format|
      if @snsstudy.update(snsstudy_params)
        format.html { redirect_to @snsstudy, notice: 'Snsstudy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @snsstudy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snsstudies/1
  # DELETE /snsstudies/1.json
  def destroy
    @snsstudy.destroy
    respond_to do |format|
      format.html { redirect_to snsstudies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_snsstudy
      @snsstudy = Snsstudy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def snsstudy_params
      #params.require(:snsstudy).permit(:name, :introduction)
      params.require(:snsstudy).permit(:name, :introduction, :email, :password, :password_confirmation)
    end

    # Before filters
    def correct_user
      @user = Snsstudy.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/snsstudies_helper.rb
module SnsstudiesHelper
end

app/views/snsstudies/_form.html.erb
<%= form_for(@snsstudy) do |f| %>
  <% if @snsstudy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snsstudy.errors.count, "error") %> prohibited this snsstudy from being saved:</h2>

      <ul>
      <% @snsstudy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
    <div class="field">
        <%= f.label :email %>
      <%= f.text_field :email %>
   </div>
      <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password %>
  </div>
      <div class="field">
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
    </div>
  <div class="field">
    <%= f.label :introduction %><br>
    <%= f.text_area :introduction %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/snsstudies/_tsubyaki_form.html.erb
<%= form_for(@tsubyaki) do |f| %>
  <div class="field">
    <%= f.text_area :content, placeholder: "新しいつぶやき..." %>
  </div>
  <%= f.submit "つぶやき", class: "btn btn-large btn-primary" %>
<% end %>

app/views/snsstudies/edit.html.erb
<h1>Editing snsstudy</h1>

<%= render 'form' %>

<%= link_to 'Show', @snsstudy %> |
<%= link_to 'Back', snsstudies_path %>

app/views/snsstudies/index.html.erb
<h1>snsstudies study all member</h1>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Introduction</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @snsstudies.each do |snsstudy| %>
      <tr>
        <td><%= snsstudy.name %></td>
        <td><%= snsstudy.introduction %></td>
        <td><%= link_to 'Show', snsstudy %></td>
        <td><%= link_to 'Edit', edit_snsstudy_path(snsstudy) %></td>
        <td><%= link_to 'Destroy', snsstudy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Snsstudy', new_snsstudy_path %>

app/views/snsstudies/new.html.erb
<h1>New snsstudy</h1>

<%= render 'form' %>

<%= link_to 'Back', snsstudies_path %>

app/views/snsstudies/old_show.html.erb
<table>
  <thead>
    <tr>
      <th>他のユーザー</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @snsstudies.each do |snsstudy| %>

      <% if snsstudy.id != @snsstudy.id then %>
      <tr>
        <td><%= snsstudy.name %>さん</td>
        <!--<td>OTHER ID=<%= snsstudy.id %></td>-->
        <!--<td>MY ID=<%= @snsstudy.id %></td>-->

        <td>
         　<% if @snsstudy.following?(snsstudy) %>
    　　　　　<!--==フォローしてる フォロー解除ボタン ==-->
　　　　　　　　　　<%= form_for(@snsstudy.relationships.find_by(followed_id: snsstudy.id),html: { method: :delete }) do |f| %>
　　　　　　　　　　<!--<input id="snsstudy_id" name="snsstudy[id]" value="<%= @snsstudy.id %>"  type="hidden" />-->
　　　　　　　　　　<%= hidden_field_tag "snsstudy[id]", @snsstudy.id %>
　　　　　　　　　　<%= f.submit "フォロー解除", class: "btn btn-large" %>
　　　　　　　　　　<% end %>
          <% else %>
           <!--==フォローしていない フォローボタン ==-->
           <!-- build　自分のIDをrelationshipsのfollower_idに　　action="/relationships" -->
           <%= form_for(@snsstudy.relationships.build(followed_id: snsstudy.id)) do |f| %>
           <!-- ==== ネストしたルーティング /snsstudy/1/relationships ====  -->
         　<%= f.hidden_field :followed_id %><!--relationship[followed_id] type="hidden" value="2"-->
          <!--<input id="snsstudy_id" name="snsstudy[id]" value="<%= @snsstudy.id %>"  type="hidden" />-->
          <%= hidden_field_tag "snsstudy[id]", @snsstudy.id %>
          <%= f.submit "フォローする", class: "btn btn-large" %>
         　<% end %>
         　<!--== フォローボタン END==-->
          <% end %>
         </td>
      </tr>
      <% end %>
      
    <% end %>
  </tbody>
</table>

app/views/snsstudies/show.html.erb
<p id="notice"><%= notice %></p>


<!--<%= debug current_user?(@snsstudy) %>-->
<!--<%= debug current_user %>-->
<div>
 <% if signed_in? %>
            <p><%= current_user.name %>さん、こんにちわ</p>
            
            <% if current_user?(@snsstudy) %>
            <%= link_to "Sign out", signout_path, method: "delete" %>
            <% end %>

          <% else %>
          <p>現在サインアウトしました</p>
 <% end %>
</div>




<p>
  <h3>
  <%= @snsstudy.name %>さんのページ</h3>
</p>

<p>
  <strong>Introduction:</strong>
  <%= @snsstudy.introduction %>
</p>




<ul>
    <li>
    フォローしている<%= @snsstudy.followed_users.count %>人
    </li>
    
    <li>
    フォローワー<%= @snsstudy.followers.count %>人
    </li>
    
</ul>

<br>

<!--current_user? サインインしているユーザーなら -->
<% if current_user?(@snsstudy) %>
  <%= form_for(@tsubyaki) do |f| %>
  <%= hidden_field_tag "snsstudy[id]", current_user.id %>
  
  <div class="field">
    <%= f.text_area :content, placeholder: "新しいつぶやき..." %>
  </div>
  <%= f.submit "つぶやき", class: "btn btn-large btn-primary" %>
<% end %>
<% else %>

<% end %>

<br>

<!--=========================================================================-->

<% unless current_user?(@snsstudy) %>
  <div>
  <% if current_user.following?(@snsstudy) %>

    <%= @snsstudy.name %>さんをフォロー解除
    <%= form_for(current_user.relationships.find_by(followed_id: @snsstudy.id),html: { method: :delete }) do |f| %>
    <%= hidden_field_tag "snsstudy[id]", current_user.id %>
    <%= f.submit "フォロー解除", class: "btn btn-large" %>
    <% end %>

  <% else %>

    <%= @snsstudy.name %>さんをフォローする
    <%= form_for(current_user.relationships.build(followed_id: @snsstudy.id)) do |f| %>
    <!-- ==== ネストしたルーティング /snsstudy/1/relationships ====  -->
    <%= f.hidden_field :followed_id %><!--relationship[followed_id] type="hidden" value="2"-->
    <%= hidden_field_tag "snsstudy[id]", current_user.id %>
    <%= f.submit "フォローする", class: "btn btn-large" %>
    <% end %>

  <% end %>
  </div>
<% end %>
<!--=========================================================================-->

<br>

<!--=========つぶやき================================================================-->
<div>
  <% if @snsstudy.tsubyakis.any? %>
    <h3>つぶやき (<%= @tsubyaki_items.count %>)</h3>
  <ul>
  <!--<%= debug @tsubyaki_items %>-->
      <% @tsubyaki_items.each do |tsubyakis| %>
      <li>
       <span><%= tsubyakis.snsstudy.name %></span>
        <span><%= tsubyakis.content %></span>
      </li>
      <% end %>
  </ul>
<%= will_paginate @tsubyakis %>
  <% end %>

</div>
<!--=========================================================================-->

<!--=========メッセのやり取りをする================================================================-->

<% unless current_user?(@snsstudy) %>
<%= link_to message_path(@snsstudy) do %>
<strong><%= @snsstudy.name %>
<%= "さんとメッセージのやり取りをする" %></strong>
<% end %>
<% end %>
<br><br>

<!--=========================================================================-->


<%= link_to 'Edit', edit_snsstudy_path(@snsstudy) %> |
<%= link_to 'Back', snsstudies_path %>